# --- Main Analysis Functions ---

#' Analyze data with a chosen LLM using a two-step approach
#'
#' @description
#' Automatically analyzes a dataset using a chosen LLM with a two-step approach. First, it generates a comprehensive
#' analysis plan. Then, it creates executable R code based on that plan. This approach allows more detailed
#' planning before code generation, which can lead to more thoughtful analysis for complex questions.
#'
#' @param data Dataset to analyze.
#' @param question Research question.
#' @param api_key API key for the selected LLM provider.
#' @param llm_provider Name of the LLM provider (e.g., "gemini", "openai", "anthropic"). Default: "gemini".
#'                    If NULL and llm_model is provided, will attempt to detect the provider from the model name.
#' @param llm_model Name of the specific LLM model to use. If NULL, defaults to a provider-specific model:
#'                  "gemini-2.0-flash" for Gemini, "gpt-3.5-turbo" for OpenAI, or "claude-3-opus-20240229" for Anthropic.
#' @param llm_provider_args A list of additional arguments for `create_llm_connection`
#'                          (e.g., list(organization_id = "org-...") for OpenAI).
#' @param llm_generation_params A list of parameters for the LLM's generation process
#'                              (e.g., list(temperature = 0.3, maxOutputTokens = 4096)).
#' @param output_file Output report file path.
#' @param include_full_data Whether to include the full dataset in prompts when small.
#' @param max_rows Maximum number of rows to consider a dataset "small".
#' @param max_cols Maximum number of columns to consider a dataset "small".
#' @param output_dir Directory where results will be saved. If NULL, defaults to "auto_stat_output".
#'
#' @return A list containing:
#' \item{plan}{The analysis plan generated by the LLM.}
#' \item{code_response}{The full response from the LLM containing the executable code.}
#' \item{extracted_code}{The executable R code extracted from the LLM response.}
#' \item{results}{A list of analysis results from executing the code, including statistical outputs and plots.}
#' \item{interpretation}{The LLM's interpretation of the results.}
#' \item{report_path}{The file path to the generated HTML report.}
#' \item{output_dir}{The directory where outputs were saved.}
#'
#' @examples
#' \dontrun{
#' # Using Anthropic's Claude with specific model
#' results <- auto_stat(
#'   data = mtcars,
#'   question = "What factors are most strongly associated with quarter-mile time?",
#'   api_key = "your_anthropic_api_key",
#'   llm_provider = "anthropic",
#'   llm_model = "claude-3-opus-20240229"
#' )
#'
#' # Using Gemini with default model
#' results <- auto_stat(
#'   data = airquality,
#'   question = "How do temperature and wind speed affect ozone levels?",
#'   api_key = "your_gemini_api_key"
#' )
#' }
#' @export
auto_stat <- function(data, question, api_key,
                      llm_provider = NULL,
                      llm_model = NULL,
                      llm_provider_args = list(),
                      llm_generation_params = list(temperature = 0.3, maxOutputTokens = 4096),
                      output_file = "auto_stat_report.html",
                      include_full_data = TRUE, max_rows = 50, max_cols = 20,
                      output_dir = NULL) {

  # First, try to detect provider from model if provider is not specified but model is
  if (is.null(llm_provider) && !is.null(llm_model)) {
    detected_provider <- detect_provider_from_model(llm_model)
    if (!is.null(detected_provider)) {
      llm_provider <- detected_provider
      message(paste("Provider detected from model name:", llm_provider))
    } else {
      # Fall back to gemini if provider cannot be detected
      llm_provider <- "gemini"
      message("Provider could not be detected from model name. Using default provider: gemini")
    }
  } else if (is.null(llm_provider)) {
    # If both provider and model are NULL, use gemini as default
    llm_provider <- "gemini"
  }

  # Now set default model based on provider if not specified
  if (is.null(llm_model)) {
    llm_model <- switch(llm_provider,
                        "gemini" = "gemini-2.0-flash",
                        "openai" = "gpt-3.5-turbo",
                        "anthropic" = "claude-3-opus-20240229",
                        "gemini-2.0-flash") # Default to gemini if provider not recognized
  }

  # Set up directory structure
  if (is.null(output_dir)) {
    output_dir <- "auto_stat_output" # Default to a standard folder name
  }

  # Ensure the base output directory exists
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }

  # Create LLM connection using the generic function
  connection_args <- c(list(provider = llm_provider, api_key = api_key, model = llm_model), llm_provider_args)
  connection <- do.call(create_llm_connection, connection_args)

  data_summary <- summarize_dataset(data, include_full_data, max_rows, max_cols)

  # Step 1: Generate analysis plan
  plan_prompt <- paste0(
    "I need to analyze a dataset with the following characteristics:\n\n", data_summary,
    "\n\nResearch question: ", question,
    "\n\nPlease provide a comprehensive yet FOCUSED analysis plan including:\n",
    "1. Recommended statistical methods with justification for their appropriateness. Focus on methods that DIRECTLY address the research question rather than including every possible approach.\n",
    "2. Required R packages (only those essential for the core analysis).\n",
    "3. A high-level outline of the analysis steps in logical order.\n",
    "4. Key assumptions for the recommended methods and ONLY the most relevant potential limitations.\n",
    "5. Suggested data preprocessing steps if truly necessary (e.g., handling missing values, transformations), but only include steps that are critical.\n",
    "6. For visualizations, plan for a SELECTIVE set of 3-4 HIGH-QUALITY plots that will provide the most insight:\n",
    "   - ONE key relationship visualization that shows the most important associations\n",
    "   - ONE diagnostic visualization that addresses a critical model assumption\n",
    "   - ONE visualization showing effect sizes or coefficient estimates with uncertainty\n",
    "   - IF needed: ONE additional visualization showing interactions or complex patterns\n",
    "   For each visualization, clearly explain what specific insight it is expected to provide.\n\n",
    "Start your response directly with the analysis plan without any introductory phrases."
  )

  analysis_plan <- send_to_llm(connection, plan_prompt,
                               data = if(include_full_data && nrow(data) <= max_rows && ncol(data) <= max_cols) data else NULL,
                               max_rows = max_rows, max_cols = max_cols,
                               llm_params = llm_generation_params)

  # Step 2: Generate executable R code
  code_prompt <- paste0(
    "Based on this analysis plan:\n\n", analysis_plan,
    "\n\nAnd this dataset summary:\n\n", data_summary,
    "\n\nPlease provide complete, executable R code that implements this analysis plan. ",
    "The code should be designed to run end-to-end without errors. ",
    "Key requirements for the R code:\n",
    "- IMPORTANT: All required packages must be automatically installed if not already available. Include a package installation function at the beginning of your code like this:\n",
    "```r\n",
    "# Function to install and load required packages\n",
    "install_and_load <- function(packages) {\n",
    "  for (package in packages) {\n",
    "    if (!require(package, character.only = TRUE, quietly = TRUE)) {\n",
    "      message(paste0('Installing package: ', package))\n",
    "      install.packages(package, dependencies = TRUE, repos = 'https://cran.rstudio.com/')\n",
    "      if (!require(package, character.only = TRUE, quietly = TRUE)) {\n",
    "        stop(paste0('Package not available: ', package))\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "# Install and load all required packages\n",
    "install_and_load(c('package1', 'package2', 'package3'))\n",
    "```\n",

    "- CRITICAL FOR VISUALIZATIONS: Create a SELECTIVE set of HIGHLY INFORMATIVE visualizations. Focus on QUALITY over quantity. For each visualization:\n",
    "  * ALWAYS assign your plot to a variable (e.g., `key_relationship_plot <- ggplot(...) + ...`) and PRINT the variable at the end of each relevant code section.\n",
    "  * DO NOT use png(), dev.off(), or ggsave() commands. Instead, create and assign plots to named variables that will be captured in the results.\n",
    "  * Each plot should reveal a specific, important insight directly relevant to the research question or model assumptions.\n",
    "  * Before creating any visualization, briefly comment on its specific purpose and what insight it's intended to provide.\n",
    "  * Carefully select only 3-4 of the MOST revealing visualizations that address the following (depending on what's most relevant to the research question):\n",
    "     1. ONE key relationship plot showing the most important predictor-outcome relationship(s)\n",
    "     2. ONE diagnostic plot addressing the most critical model assumption\n",
    "     3. ONE plot showing effect sizes, variable importance, or coefficient estimates with uncertainty\n",
    "     4. IF appropriate: ONE plot showing interactions, non-linear relationships, or predictions\n",
    "  * Use informative titles, clear labels, appropriate scales, and concise legends\n",
    "  * Use a readable theme (e.g., theme_minimal(), theme_bw()) and colorblind-friendly colors when needed\n",

    "- Replace 'package1', 'package2', etc. with the actual packages needed for the analysis.\n",
    "- Implement robust error handling (e.g., using `tryCatch` for potentially problematic steps). If a step fails, the script should report the error gracefully and attempt to continue with subsequent independent steps if possible.\n",
    "- Ensure that any important results or objects created (e.g., models, test results, data frames from transformations) are assigned to clearly named variables. Print summaries or key outputs of these results where appropriate for verification.\n",
    "- Include comments not just for section headers, but also to explain complex logic or non-obvious choices within the code.\n",
    "- If the analysis plan mentioned checking assumptions (e.g., for regression), include code to perform these checks (e.g., residual plots, normality tests).\n",
    "- If any methods involving randomness are used (e.g., bootstrapping), set a seed (e.g., `set.seed(123)`) at the beginning of the script for reproducibility.\n",
    "- When referring to columns in the 'data' data frame, use explicit indexing like `data$column_name` or `data[['column_name']]`.\n",
    "- Make sure the code is properly formatted with clear section headers as comments (e.g., '# 1. Data Loading', '# 2. Exploratory Data Analysis').\n",
    "- Do not include any placeholder code or TODOs - only provide code that will actually run.\n",
    "- The dataset is available as the 'data' variable.\n",
    "- If creating directories, ensure that the code creates them if they don't exist using `dir.create(path, recursive = TRUE, showWarnings = FALSE)`.\n",
    "IMPORTANT: Format your R code inside a single R code block starting with ```R and ending with ```."
  )

  executable_code_response <- send_to_llm(connection, code_prompt,
                                          data = if(include_full_data && nrow(data) <= max_rows && ncol(data) <= max_cols) data else NULL,
                                          max_rows = max_rows, max_cols = max_cols,
                                          llm_params = llm_generation_params)

  extracted_code <- process_code(executable_code_response)

  if (length(extracted_code) == 0 || all(sapply(extracted_code, function(x) nchar(trimws(x))) < 100)) {
    code_prompt_retry <- paste0(
      "I need R code to analyze a dataset. Please provide only the executable R code inside triple backticks (```R ... ```). ",
      "No explanations or commentary outside the R code block itself - just pure R code that will run directly when copied to an R script. ",
      "The dataset summary is:\n\n", data_summary,
      "\n\nThe research question is: ", question,
      "\n\nThe code should implement this analysis plan:\n\n", analysis_plan,
      "\n\nPlease format your response like this:\n\n```R\n# Your R code here\nset.seed(123) # Example for reproducibility\n# ... rest of the code ...\n```"
    )
    executable_code_response <- send_to_llm(connection, code_prompt_retry,
                                            data = if(include_full_data && nrow(data) <= max_rows && ncol(data) <= max_cols) data else NULL,
                                            max_rows = max_rows, max_cols = max_cols,
                                            llm_params = llm_generation_params)
    extracted_code <- process_code(executable_code_response)
  }

  if (length(extracted_code) == 0 || all(sapply(extracted_code, function(x) nchar(trimws(x))) < 100)) {
    extracted_code <- executable_code_response
  }

  cat("Executing analysis code...\n")
  results <- tryCatch({
    execute_code(data, extracted_code)
  }, error = function(e) {
    warning("Error executing initial code: ", e$message)
    return(list(initial_execution_error = e$message))
  })

  if (length(results) == 0 || !is.null(results$initial_execution_error)) {
    cat("Initial code execution failed or returned no results. Adding basic statistics...\n")
    current_results <- if(is.null(results$initial_execution_error)) list() else results
    # ... (basic statistics generation logic remains the same) ...
    tryCatch({
      current_results$data_summary_stats <- data.frame(
        Variable = names(data),
        Type = sapply(data, function(x) class(x)[1]),
        MissingValues = sapply(data, function(x) sum(is.na(x))),
        stringsAsFactors = FALSE
      )
      numeric_cols <- sapply(data, is.numeric)
      if (any(numeric_cols)) {
        for (col_name in names(data)[numeric_cols]) { # Renamed col to col_name for clarity
          col_data <- data[[col_name]]
          current_results[[paste0(col_name, "_numeric_summary")]] <- summary(col_data)
        }
      }
      results <- current_results
    }, error = function(e_basic) { # Renamed e to e_basic
      warning("Failed to generate basic statistics: ", e_basic$message)
      results <- if(is.null(results$initial_execution_error)) list(basic_stats_error = e_basic$message) else c(results, basic_stats_error = e_basic$message)
    })
  }

  execution_errors <- grep("_error$", names(results), value = TRUE)
  has_initial_error <- !is.null(results$initial_execution_error)

  if (length(execution_errors) > 0 || has_initial_error) {
    error_messages <- character(0)
    if(has_initial_error) {
      error_messages <- c(error_messages, paste("Initial Execution Error:", results$initial_execution_error))
    }
    error_messages <- c(error_messages, sapply(execution_errors, function(e_name) paste(e_name, ":", results[[e_name]])))
    full_error_message <- paste(error_messages, collapse = "\n")

    fix_prompt <- paste0(
      "The R code previously provided had the following errors when executed:\n\n", full_error_message,
      "\n\nPlease review the original analysis plan and dataset summary, then provide a complete, corrected, and working R script to address these errors. ",
      "Follow all the requirements for the R code mentioned previously (error handling, comments, reproducibility, explicit variable usage, section headers, no placeholders, visualizations, 'data' variable, ```R formatting).",
      "\n\nAdditionally, please ensure your updated code follows these critical requirements:\n",
      "1. Include the package installation function to automatically install missing packages.\n",
      "2. Create ONLY 3-4 highly informative visualizations, assigned to variables and printed (not saved to files).\n",
      "3. For statistical results, be SELECTIVE - retain only ONE final model with associated coefficient and fit tables.\n",
      "4. Minimize redundancy in all outputs, keeping only the most informative elements.\n",
      "\n\nOriginal Analysis Plan:\n", analysis_plan,
      "\n\nDataset summary:\n", data_summary,
      "\n\nIMPORTANT: Format your R code inside a single R code block starting with ```R and ending with ```."
    )
    fixed_code_response <- send_to_llm(connection, fix_prompt,
                                       data = if(include_full_data && nrow(data) <= max_rows && ncol(data) <= max_cols) data else NULL,
                                       max_rows = max_rows, max_cols = max_cols,
                                       llm_params = llm_generation_params)
    extracted_fixed_code <- process_code(fixed_code_response)

    if (length(extracted_fixed_code) > 0 && nchar(trimws(extracted_fixed_code[[1]])) > 100) {
      cat("Executing fixed code...\n")
      results_fixed <- tryCatch({
        execute_code(data, extracted_fixed_code)
      }, error = function(e_fixed) { # Renamed e to e_fixed
        warning("Error executing fixed code: ", e_fixed$message)
        return(c(results, fixed_code_execution_error = e_fixed$message))
      })
      if (length(results_fixed) > 0 && is.null(results_fixed$fixed_code_execution_error)) {
        results <- results_fixed
        executable_code_response <- fixed_code_response
      } else {
        results$fixed_code_attempted <- TRUE
        results$fixed_code_response <- fixed_code_response
        if(!is.null(results_fixed$fixed_code_execution_error)){
          results$fixed_code_final_error <- results_fixed$fixed_code_execution_error
        }
      }
    } else {
      results$fixed_code_extraction_failed <- TRUE
    }
  }

  cat("Generating result summary...\n")
  summary_text <- tryCatch({
    summarize_results(results, data)
  }, error = function(e_summary) { # Renamed e to e_summary
    warning("Error generating result summary: ", e_summary$message)
    # ... (fallback summary text remains the same) ...
    paste0(
      "The analysis was performed on a dataset with ", nrow(data), " observations and ",
      ncol(data), " variables.\nKey variables include: ",
      paste(names(data), collapse = ", "), ".\n",
      "Error during results summarization: ", e_summary$message
    )
  })

  interpret_prompt <- paste0(
    "You are an expert statistician writing the interpretation section for a professional statistical analysis report. ",
    "Your audience consists of researchers, data analysts, and decision-makers who require clear, accurate, and actionable insights.\n\n",
    "Research Question: ", question, "\n\n",
    "Analysis Plan Overview:\n", analysis_plan, "\n\n",
    "Analysis Results (includes statistical outputs and detailed descriptions of visualizations):\n\n", summary_text, "\n\n",
    "Write a professional interpretation that directly addresses the research question. Be precise, concise, and focus on the most important findings. ",
    "Avoid unnecessary technical jargon while maintaining statistical rigor. Structure your response using these sections:\n\n",
    "**Executive Summary**\n",
    "Provide a 2-3 sentence summary that directly answers the research question with key quantitative findings.\n\n",
    "**Key Findings from Visualizations**\n",
    "Briefly describe the main insights from each important visualization, focusing on what they reveal about the relationships in the data.\n\n",
    "**Statistical Results**\n",
    "Report the most important statistical findings with appropriate context. Include effect sizes, confidence intervals, and p-values where relevant, but interpret their practical meaning.\n\n",
    "**Effect Sizes and Practical Significance**\n",
    "Discuss the magnitude of observed effects and their real-world implications. Distinguish between statistical and practical significance.\n\n",
    "**Limitations**\n",
    "Acknowledge key limitations that affect the interpretation of results, including methodological constraints and data quality issues.\n\n",
    "**Conclusions**\n",
    "Provide clear, evidence-based conclusions that directly address the research question.\n\n",
    "**Recommendations**\n",
    "Suggest concrete next steps for research or practical applications based on the findings.\n\n",
    "Requirements:\n",
    "- Start directly with the '**Executive Summary**' section - no introductory text\n",
    "- Provide comprehensive coverage of all important findings - prioritize completeness and usefulness over brevity\n",
    "- Focus on interpretation and implications, not just restating numbers\n",
    "- Use clear, professional language appropriate for a technical audience\n",
    "- Include specific quantitative findings to support conclusions\n",
    "- Provide thorough analysis in each section as needed to fully address the research question\n",
    "- Avoid hedging language unless uncertainty is genuinely warranted"
  )
  interpretation <- send_to_llm(connection, interpret_prompt, llm_params = llm_generation_params)

  cat("Generating report...\n")
  # NEW VERSION:
  report_info <- generate_enhanced_report(
    data = data, question = question, analysis_plan = analysis_plan,
    executable_code = if(is.list(extracted_code)) paste(extracted_code, collapse="\n\n") else extracted_code,
    results = results, interpretation = interpretation,
    output_file = file.path(output_dir, output_file),
    output_dir = output_dir,
    llm_connection = connection  # Add this line
  )

  return(list(
    plan = analysis_plan, code_response = executable_code_response,
    extracted_code = extracted_code, results = results,
    interpretation = interpretation, report_path = report_info$report_path,
    output_dir = report_info$output_dir
  ))
}
